# Reporting

To run all at once – please choose: "Cell" => "Run All" 

To run cell by cell – please enter "Shift + Enter" for each cell in this notebook.

To reset everything – please choose: "Kernel" => "Restart" OR "Kernel" => "Restart & Clear Output" OR "Kernel" => "Restart & Run All"

Each cell could be edited and then run as described above.  

Comments are started with "#".

In [ ]:
from reporting import Reporting

## Initialise user's account

In [2]:
# Please set the following parameters.
name = "John Smith" # user name
portfolio_id = "AAA" # portfolio name (each user could have more than one portfolio)
date = "2015-10-20" # date of account
currency = "EUR" # account currency
initial_balance = 130000

In [3]:
account = {name: [Reporting(date, portfolio_id, initial_balance, currency)]}

## Buy and sell some assetes

In [4]:
# Note 1: here we set amount to spend; the quantity is calculated from amount comissions/fees and price. 
# Please let me know if, instead, we have to set quantity instead.  
# Note 2: I assume that the commission is a multiplier, and the fee is an additive constant. 
# Please let me know if there should be other definitions.

In [5]:
asset_info = {"date": "2015-10-22", 
            "bank": "Bper", 
            "isin": "IT0000388907", 
            "title": "Arca Azioni Italia",
            "price": 20.4554,
            "nav": 20.4554,
            "fee": 0,
            "commission": 0,
            "currency": "EUR",
             "maturity": ""}
amount = 12737.37 # amount in EUR to spend 
account[name][0].buy(asset_info, amount, 1) # buy

In [6]:
asset_info = {"date": "2015-10-22", 
            "bank": "Bper", 
            "isin": "IT0000380029", 
            "title": "Arca RR",
            "price": 11.176,
            "nav": 11.176,
            "fee": 0,
            "commission": 0,
            "currency": "EUR",
             "maturity": ""}
amount = 33760.32 # amount in EUR to spend
account[name][0].buy(asset_info, amount, 1) # buy

In [7]:
asset_info = {"date": "2015-12-11", 
            "bank": "Bper", 
            "isin": "IT0000380029", 
            "title": "Arca RR",
            "price": 11.109,
            "nav": 11.109,
            "fee": 0,
            "commission": 0,
            "currency": "EUR",
             "maturity": ""}
amount = 29996.5 # amount in EUR to spend
account[name][0].buy(asset_info, amount, 1) # buy

In [8]:
asset_info = {"date": "2016-02-22", 
            "bank": "Bper", 
            "isin": "IT0005104473", 
            "title": "CctEu 15Giu22 TV",
            "price": 100.24,
            "nav": 100.24,
            "fee": 0,
            "commission": 0.003,
            "currency": "EUR",
             "maturity": "2022-12-31"}
amount = 50330.3394 # amount in EUR to spend
account[name][0].buy(asset_info, amount, 1) # buy

In [9]:
asset_info = {"date": "2016-02-24", 
            "bank": "Bper", 
            "isin": "IT0000384641", 
            "title": "Arca TE Titoli Esteri",
            "price": 20.876,
            "nav": 20.876,
            "fee": 0,
            "commission": 0,
            "currency": "EUR",
             "maturity": ""}
amount = 9996.49 # amount in EUR to spend
account[name][0].buy(asset_info, amount, 1) # buy

In [10]:
asset_info = {"date": "2016-10-20", 
            "bank": "Bper", 
            "isin": "IT0001033486", 
            "title": "Arca Azioni Europa",
            "price": 13.296,
            "nav": 13.296,
            "fee": 0,
            "commission": 0,
            "currency": "EUR",
             "maturity": ""}
amount = 8000 # amount in EUR to spend
account[name][0].buy(asset_info, amount, 1) # buy

In [11]:
asset_info = {"date": "2016-12-06", 
            "bank": "Bper", 
            "isin": "IT0005104473", 
            "title": "CctEu 15Giu22 TV",
            "price": 99.5,
            "nav": 99.5,
            "fee": 0,
            "commission": 0,
            "currency": "EUR",
             "maturity": ""}
amount = 19938.5 # amount in EUR to spend
account[name][0].sell(asset_info, amount, 1) # sell

In [12]:
asset_info = {"date": "2017-03-06", 
            "bank": "Bper", 
            "isin": "IT0000384641", 
            "title": "Arca TE Titoli Esteri",
            "price": 22.841,
            "nav": 22.841,
            "fee": 0,
            "commission": 0,
            "currency": "EUR",
             "maturity": ""}
amount = 4914.77 # amount in EUR to spend
account[name][0].sell(asset_info, amount, 1) # sell

In [13]:
asset_info = {"date": "2017-10-20", 
            "bank": "Bper", 
            "isin": "FR0012386696", 
            "title": "Lyxor Barc Float Rate Eur 0-7y",
            "price": 101.05,
            "nav": 101.05,
            "fee": 0,
            "commission": 0,
            "currency": "EUR",
             "maturity": "2022-12-31"}
amount = 19001.35 # amount in EUR to spend
account[name][0].buy(asset_info, amount, 1) # buy

### Current account table

In [14]:
account[name][0].current_account

,Date,Operation,Cash Flow,Balance,Record
0,2015-10-20,Deposit,130000.0000,130000.0000,Deposit
1,2015-10-22,Buy,12737.3700,117262.6300,Buy: Arca Azioni Italia ISIN: IT0000388907
2,2015-10-22,Buy,33760.3200,83502.3100,Buy: Arca RR ISIN: IT0000380029
3,2015-12-11,Buy,29996.5000,53505.8100,Buy: Arca RR ISIN: IT0000380029
4,2016-02-22,Buy,50330.3394,3175.4706,Buy: CctEu 15Giu22 TV ISIN: IT0005104473
5,2016-02-24,Buy,3175.4706,0.0000,Buy: Arca TE Titoli Esteri ISIN: IT0000384641
6,2016-12-06,Sell,19938.5000,19938.5000,Sell: CctEu 15Giu22 TV ISIN: IT0005104473
7,2017-03-06,Sell,3175.4706,23113.9706,Sell: Arca TE Titoli Esteri ISIN: IT0000384641
8,2017-10-20,Buy,19001.3500,4112.6206,Buy: Lyxor Barc Float Rate Eur 0-7y ISIN: FR00...

### Buy / sell table

In [15]:
account[name][0].buysell

,Portfolio,Bank,Date,ISIN,Currency,Exchange Rate,Title,Operation,Quantity,Price,NAV,Fee,Commission,Cost
0,AAA,Bper,2015-10-22,IT0000388907,EUR,1,Arca Azioni Italia,Buy,622.689852,20.4554,20.4554,0,0,12737.3700
1,AAA,Bper,2015-10-22,IT0000380029,EUR,1,Arca RR,Buy,3020.787402,11.1760,11.1760,0,0,33760.3200
2,AAA,Bper,2015-12-11,IT0000380029,EUR,1,Arca RR,Buy,2700.198038,11.1090,11.1090,0,0,29996.5000
3,AAA,Bper,2016-02-22,IT0005104473,EUR,1,CctEu 15Giu22 TV,Buy,500.592063,100.2400,100.2400,0,0.003,50330.3394
4,AAA,Bper,2016-02-24,IT0000384641,EUR,1,Arca TE Titoli Esteri,Buy,152.111065,20.8760,20.8760,0,0,3175.4706
5,AAA,Bper,2016-12-06,IT0005104473,EUR,1,CctEu 15Giu22 TV,Sell,200.386935,99.5000,99.5000,0,0,19938.5000
6,AAA,Bper,2017-03-06,IT0000384641,EUR,1,Arca TE Titoli Esteri,Sell,139.025025,22.8410,22.8410,0,0,3175.4706
7,AAA,Bper,2017-10-20,FR0012386696,EUR,1,Lyxor Barc Float Rate Eur 0-7y,Buy,188.039090,101.0500,101.0500,0,0,19001.3500

## Add dividends / coupons

In [16]:
interest_info = {"date": "2017-10-20",
                "isin": "FR0012386696",
                "title": "Lyxor Barc Float Rate Eur 0-7y",
                "quantity": 1000,
                "amount": 190,
                "currency": "EUR"}
account[name][0].interest(interest_info)

## Deposit / withdraw

In [17]:
amount = 10000 # EUR
account[name][0].deposit("2017-11-14", amount) # deposit
amount = 5000 # EUR
account[name][0].withdraw("2017-11-17", amount) # withdraw

### Current account and Buy / sell tables

In [18]:
account[name][0].current_account

,Date,Operation,Cash Flow,Balance,Record
0,2015-10-20,Deposit,130000.0000,130000.0000,Deposit
1,2015-10-22,Buy,12737.3700,117262.6300,Buy: Arca Azioni Italia ISIN: IT0000388907
2,2015-10-22,Buy,33760.3200,83502.3100,Buy: Arca RR ISIN: IT0000380029
3,2015-12-11,Buy,29996.5000,53505.8100,Buy: Arca RR ISIN: IT0000380029
4,2016-02-22,Buy,50330.3394,3175.4706,Buy: CctEu 15Giu22 TV ISIN: IT0005104473
5,2016-02-24,Buy,3175.4706,0.0000,Buy: Arca TE Titoli Esteri ISIN: IT0000384641
6,2016-12-06,Sell,19938.5000,19938.5000,Sell: CctEu 15Giu22 TV ISIN: IT0005104473
7,2017-03-06,Sell,3175.4706,23113.9706,Sell: Arca TE Titoli Esteri ISIN: IT0000384641
8,2017-10-20,Buy,19001.3500,4112.6206,Buy: Lyxor Barc Float Rate Eur 0-7y ISIN: FR00...
9,2017-10-20,Dividend / Coupon,190.0000,4302.6206,Title: FR0012386696 EUR Qty: 1000 (Lyxor Barc ...
10,2017-11-14,Deposit,10000.0000,14302.6206,Deposit
11,2017-11-17,Withdraw,5000.0000,9302.6206,Withdraw

In [19]:
account[name][0].buysell

,Portfolio,Bank,Date,ISIN,Currency,Exchange Rate,Title,Operation,Quantity,Price,NAV,Fee,Commission,Cost
0,AAA,Bper,2015-10-22,IT0000388907,EUR,1,Arca Azioni Italia,Buy,622.689852,20.4554,20.4554,0,0,12737.3700
1,AAA,Bper,2015-10-22,IT0000380029,EUR,1,Arca RR,Buy,3020.787402,11.1760,11.1760,0,0,33760.3200
2,AAA,Bper,2015-12-11,IT0000380029,EUR,1,Arca RR,Buy,2700.198038,11.1090,11.1090,0,0,29996.5000
3,AAA,Bper,2016-02-22,IT0005104473,EUR,1,CctEu 15Giu22 TV,Buy,500.592063,100.2400,100.2400,0,0.003,50330.3394
4,AAA,Bper,2016-02-24,IT0000384641,EUR,1,Arca TE Titoli Esteri,Buy,152.111065,20.8760,20.8760,0,0,3175.4706
5,AAA,Bper,2016-12-06,IT0005104473,EUR,1,CctEu 15Giu22 TV,Sell,200.386935,99.5000,99.5000,0,0,19938.5000
6,AAA,Bper,2017-03-06,IT0000384641,EUR,1,Arca TE Titoli Esteri,Sell,139.025025,22.8410,22.8410,0,0,3175.4706
7,AAA,Bper,2017-10-20,FR0012386696,EUR,1,Lyxor Barc Float Rate Eur 0-7y,Buy,188.039090,101.0500,101.0500,0,0,19001.3500

### Current position tables

In [20]:
# Current position.
account[name][0].portfolio

,ISIN,Currency,Maturity,Quantity,Price,Exchange Rate,Value Gross,Value Net,Weight
Title,,,,,,,,,
Arca Azioni Italia,IT0000388907,EUR,,622.69,20.4554,1,12737.4,12737.4,0.0943236
Arca RR,IT0000380029,EUR,,5720.99,11.109,1,63756.8,63756.8,0.472136
CctEu 15Giu22 TV,IT0005104473,EUR,2022-12-31,300.205,99.5,1,30391.8,30240.8,0.223942
Lyxor Barc Float Rate Eur 0-7y,FR0012386696,EUR,2022-12-31,188.039,101.05,1,19001.3,19001.3,0.14071
Cash,NaN,NaN,NaN,9302.62,NaN,NaN,9302.62,9302.62,0.0688884